import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectRoot = path.resolve(__dirname, '..');

// Ollama API configuration (defaulting to the local Proxmox VM instance per Pandaface OS setup)
const OLLAMA_URL = 'http://localhost:11434/api/chat';
const MODEL = 'llama3.2'; // Or whichever model the user prefers locally (e.g., mistral, llama3)

async function generatePageData(pageType, strategyData, siteConfig) {
  console.log(`🧠 Prompting Ollama to generate ${pageType} page architecture...`);

  // Build the system prompt teaching the LLM about our Lego blocks
  const systemPrompt = `You are the lead conversion copywriter and site architect for Pandaface Digital. 
Your job is to generate a high-converting landing page schema for a local service business.
You MUST output raw, valid JSON only. Do not wrap in markdown tags or add explanatory text.

The available "Lego Block" components you can use in the "blocks" array are:
1. "Hero": Requires { heroClass: string ("home"|"standard"), h1: string (HTML allowed), desc: string, label: string }
2. "TrustBar": Requires { signals: [{ icon: "award"|"shield"|"star"|"license", text: string, subtext: string }] }
3. "WhyChooseUs": Requires { title: string, subtitle: string, reasons: [{ icon: "check"|"clock"|"shield"|"user"|"star"|"zap", headline: string, description: string }] }
4. "ProcessWalkthrough": Requires { title: string, subtitle: string, steps: [{ title: string, description: string }] }
5. "Testimonials": Requires { title: string, subtitle: string, reviews: [{ author: string, location: string, service: string, text: string, rating: number }] }
6. "ServiceList": Requires { title: string, subtitle: string, services: [{ title: string, description: string, link: string, icon: "bolt"|"home"|"business"|"tool" }] }
7. "CityPills": Requires { variant: "light"|"dark" }
8. "QuoteForm": Requires { formTag: string }

The overall JSON schema must be:
{
  "slug": "${pageType === 'home' ? 'index' : pageType}",
  "title": "Page Title for SEO",
  "description": "Meta description",
  "blocks": [ /* array of block objects here */ ]
}

Client Strategy Context:
${strategyData}

Business Info:
${JSON.stringify(siteConfig.business, null, 2)}`;

  const userPrompt = `Generate the optimal JSON funnel layout for the ${pageType} page. Ensure the copy is persuasive and localized to their service area.`;

  try {
    const response = await fetch(OLLAMA_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        model: MODEL,
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: userPrompt }
        ],
        stream: false,
        format: "json" // Force JSON mode if supported by the model
      })
    });

    if (!response.ok) {
      throw new Error(`Ollama API error: ${response.status} ${response.statusText}`);
    }

    const data = await response.json();
    return data.message.content;
  } catch (error) {
    console.warn('⚠️ Ollama is offline or model missing. Falling back to mock data for demonstration.');
    
    // MOCK FALLBACK for architecture verification
    return JSON.stringify({
      slug: pageType === 'home' ? 'index' : pageType,
      title: `${pageType.charAt(0).toUpperCase() + pageType.slice(1)} - Bam Electric`,
      description: `The ${pageType} page for Bam Electric's Lego Block site.`,
      blocks: [
        {
          type: "Hero",
          data: {
            heroClass: "standard",
            h1: `Generated <em class='serif accent'>${pageType}</em> Page`,
            desc: "This page was auto-generated by the AI orchestrator script using the Lego Block JSON engine."
          }
        },
        {
          type: "ServiceList",
          data: {
            title: "Generated Services",
            services: [
              { title: "Residential Wiring", description: "Home automation and wiring.", link: "/services/residential", icon: "home" },
              { title: "Commercial Power", description: "Panel upgrades for businesses.", link: "/services/commercial", icon: "business" }
            ]
          }
        }
      ]
    });
  }
}

async function run() {
  console.log('🚀 Starting Pandaface "Drive Mode" Site Generation...');

  try {
    // 1. Read strategy and config
    const strategyPath = path.resolve(projectRoot, '.ai', 'strategy.md');
    const strategyData = await fs.readFile(strategyPath, 'utf8');
    
    const configPath = path.resolve(projectRoot, 'src', 'data', 'site-config.json');
    const siteConfig = JSON.parse(await fs.readFile(configPath, 'utf8'));

    // 2. Define pages to generate
    const pagesToGenerate = ['home', 'services', 'about'];
    const outputDir = path.resolve(projectRoot, 'src', 'data', 'pages');

    // Ensure output dir exists
    await fs.mkdir(outputDir, { recursive: true });

    // 3. Generate and save each page
    for (const pageName of pagesToGenerate) {
      const fileName = `${pageName}.json`;
      const outputPath = path.join(outputDir, fileName);
      
      const jsonContent = await generatePageData(pageName, strategyData, siteConfig);
      
      // Basic validation to ensure it's parseable JSON before saving
      try {
        JSON.parse(jsonContent);
        await fs.writeFile(outputPath, jsonContent);
        console.log(`✅ Successfully generated and saved: ${fileName}`);
      } catch (parseError) {
        console.error(`❌ Ollama returned invalid JSON for ${pageName}. Skipping save.`);
        console.log('Raw output snippet:', jsonContent.substring(0, 200));
      }
    }
    
    console.log('\n🎉 Generation Complete! Run `npm run build` to compile the site.');

  } catch (error) {
    console.error('Fatal error during generation:', error);
  }
}

run();
